### ISSUE TITLE
A issue about Model.py

### ISSUE THREAD

**Issue by RichardHGL** [1049451037/GCN-Align#1]
In Model.py, the matrix M seems to be not same as the description of your paper.
Is that turns to be better results?
![image](https://user-images.githubusercontent.com/20337906/48055627-fd1e0500-e1ea-11e8-952e-9ca0b355c808.png)

![image](https://user-images.githubusercontent.com/20337906/48055744-44a49100-e1eb-11e8-88c0-4ea93efa7a57.png)

**Comment by 1049451037** [comment]
hi @RichardHGL , thank you for your issue. I am sorry that it was a mistake in the paper.

The motivation is that we want to allocate different attention for the different type of relations. ***func*** and ***ifunc*** make sence in some way but not raw ***func*** and ***ifunc***.

We empirically set the power of ***func*** and ***ifunc*** *alpha*=1/4, which makes better results as you said.

Intuitively, the value of aij with ***func*** and ***ifunc*** will be closer to binary aij while *alpha* being smaller.

**Comment by 1049451037** [comment]
Actually, the power of func and ifunc is a hyperparameter, we find *1/4* is better later.
