### ISSUE TITLE
关于实验结果和论文结果的一些问题

### ISSUE THREAD

**Issue by PrimaLuz** [1049451037/GCN-Align#9]
你好，我发现论文中Hit指标不分“left”和“right”，而实验结果分为“left”和“right”。请问是否是“left”+“right” / 2 = 论文结果吗？

**Comment by 1049451037** [comment]
你好，论文里的结果也是分left和right的，比如中英数据有ZH->EN和EN->ZH

**Comment by PrimaLuz** [comment]
哦！万分感谢！是我的理解有误，原来left和right代指了不同的语言。此外，祝你新年快乐，科研顺利！
